import React from "react";
import CardComp from "../components/CardComp/CardComp";
import { CardData } from "../components/Data/Data";
import Head from "next/head";
import { Card, Checkbox } from "antd";
import Image from "next/image";

const borrow = () => {
  
  return (
    <>
      <Head>
        <title>LAR - DAPP - Borrow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-10 mt-1">
        <h1 className="font-semibold text-[28px] leading-[44px] font-jakarta mb-5 text-white">
          Borrow instantly
        </h1>

        <div className="mb-14 flex gap-4">
          {CardData.map((e) => {
            return (
              <CardComp
                key={e.id}
                img={e.img}
                listed={e.listed}
                name={e.name}
                x2y2={e.x2y2}
                borrowDay={e.borrowDay}
                weth={e.weth}
                apr={e.apr}
                acceptD={e.acceptD}
                offerD={e.offerD}
                offerBtn={e.offerBtn}
              />
            );
          })}
        </div>

        <h1 className="font-semibold text-[28px] leading-[44px] font-jakarta mb-5 text-white">
          List to receive more offers
        </h1>

        <div className="mb-14 flex gap-4">
          <Card
            style={{ width: 185 }}
            cover={<Image src={AllStarCardImg} alt="img" />}
            bordered={false}
          >
            <div className="mb-[6px] flex justify-between items-center">
              <p className="font-jakarta font-normal text-[10px] text-white leading-5">
                AllStarz #8946
              </p>

              <Checkbox />
            </div>
            <div className="flex justify-between items-center">
              <p className="font-jakarta font-extralight text-[10px] text-white leading-3">
                Borrow
              </p>
            </div>
            <div className="flex justify-between items-center mb-1">
              <span className="w-[71px] h-1 rounded-[4px] bg-closeBg"></span>

              <button className="px-[5px] py-[3px] rounded-lg bg-transparent text-xs font-jakarta font-medium text-white border border-darkBorderG">
                List
              </button>
            </div>
          </Card>
        </div>

        <h1 className="font-semibold text-[28px] leading-[44px] font-jakarta mb-5 text-white">
          Can’t be used as collateral
        </h1>

        <div className="mb-14 flex gap-4">
          <Card
            style={
              disabled
                ? {
                    pointerEvents: "none",
                    opacity: "0.4",
                    width: 185,
                    cursor: "not-allowed",
                  }
                : { width: 185 }
            }
            cover={<Image src={AllStarCardImg} alt="img" />}
            bordered={false}
          >
            <div className="mb-[6px] flex justify-between items-center">
              <p className="font-jakarta font-normal text-[10px] text-white leading-5">
                AllStarz #8946
              </p>

              <Checkbox />
            </div>
            <div className="flex justify-between items-center">
              <p className="font-jakarta font-extralight text-[10px] text-white leading-3">
                Borrow
              </p>
            </div>
            <div className="flex justify-between items-center mb-1">
              <span className="w-[71px] h-1 rounded-[4px] bg-closeBg"></span>

              <button className="px-[5px] py-[3px] rounded-lg bg-transparent text-xs font-jakarta font-medium text-white border border-darkBorderG">
                List
              </button>
            </div>
          </Card>
        </div>
      </div>
    </>
  );
};

export default borrow;
