import React, { useEffect, useState } from "react";
import CardComp from "../components/CardComp/CardComp";
import { CardData } from "../components/Data/Data";
import Head from "next/head";
import { Card, Checkbox } from "antd";
import Image from "next/image";
import { useAccount } from "wagmi";

import AllStarCardImg from "../public/assets/AllStarCardImg.png";
import ModalComp from "../components/Modal/ModalComp";
import ListingSummary from "../components/ListingSummary/ListingSummary";
import LoanSummary from "../components/LoanSummary/LoanSummary";
import BorrowTable from "../components/Tables/BorrowTable";

const Borrow = (disabled = true) => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const { address } = useAccount();

  const showModal = () => {
    setIsModalOpen(true);
  };
  const [ownedNFTs, setOwnedNFTs] = useState([]);

  const getCannotBeUsedAsCollateralNFTsList = () => {
    // call api endpoint nft which will return all the list of nfts which are currenlty owned by the wallet address

    // filter out the nfts which are not whitelisted
  };





  useEffect(() => {
    if (address) {
      fetch('/api/nft',
        {
          method: 'POST', // or 'PUT'
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            address,
          }),
        }
      )
        .then((res) => res.json())
        .then((res) => {
          setOwnedNFTs(res.ownedNfts);
          console.log(res.ownedNfts)
        });
    }

  }, [address]);

  return (
    <>
      <Head>
        <title>LAR - DAPP - Borrow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BorrowTable />

      <ModalComp
        isModalOpen={isModalOpen}
        setIsModalOpen={setIsModalOpen}
        content={<LoanSummary setIsModalOpen={setIsModalOpen} />}
      // content={<ListingSummary />}
      />
    </>
  );
};

export default Borrow;
