import Head from "next/head";
import LoanDetails from "../components/LoanStatics/LoanDetails";
import ManageTable from "../components/Tables/ManageTable";
import BorrowTable from "../components/Tables/BorrowTable";

export default function Home() {
  return (
    <>
      <Head>
        <title>LAR - DAPP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mb-20">
        <LoanDetails />
        <ManageTable />
        <BorrowTable />
      </main>
    </>
  );
}
